main = "index.js"
compatibility_date = "2022-05-25"

[env.dev]
name = "chiquito-rest-dev"
workers_dev = true

[env.production]
name = "chiquito-rest"
workers_dev = false
minify = true
route = "api.chiquito.rest/*"