#:schema node_modules/wrangler/config-schema.json
name = "chiquito-rest"
main = "src/index.ts"

compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
minify = true
route = "api.chiquito.rest/*"